namespace ASB.Admin.v1.Models
{
    /// <summary>
    /// Model representing a user in the admin application. This model is used to structure the data related to users that is sent to and received from the client. It typically contains properties that are relevant for displaying user information in the admin interface, such as ID, username, and email address.
    /// </summary>
    public class UserModel
    {
        /// <summary>
        /// Unique identifier for the user. This is typically generated by the database and is used to reference the user in other parts of the application.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// The username of the user. This is a unique identifier for the user that is used for authentication and display purposes. It should be unique across all users in the system.
        /// </summary>
        public required string Username { get; set; }
        /// <summary>
        /// The email address of the user. This is used for communication and may also be used for authentication purposes. It should be unique across all users in the system.
        /// </summary>
        public required string Email { get; set; }
        public List<int> UserGroupIds { get; set; } = [];
    }
}