namespace ASB.Services.v1.Dtos
{
    /// <summary>
    /// Data Transfer Object (DTO) representing a country. This DTO is used to transfer country data between the service layer and the controllers. It typically contains properties that are relevant for the UI or API responses, such as the country's name and code.
    /// </summary>
    public class CountryDto
    {
        /// <summary>
        /// Gets or sets the name of the country. This property is used to display the country's name in the UI or API responses.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the ISO code of the country. This property is used for identification purposes and may be required for certain operations, such as filtering or sorting countries.
        /// </summary>
        public string Code { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the market associated with the country. This property is used to categorize countries into different markets, which can be useful for reporting or analytics purposes.
        /// </summary>
        /// <remarks>
        /// The market property can be used to group countries into regions or economic zones, such as "North America", "Europe", or "Asia". This can help in analyzing data based on geographical regions.
        /// </remarks>
        public string Market { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the unique identifier for the country. This property is used internally to reference the country in the database and may not be exposed in all API responses.
        /// </summary>
        /// <remarks>
        /// The Id property is typically generated by the database and is used to uniquely identify each country. It may not be necessary to include this property in all API responses, especially if the client does not need to reference the country by its ID.
        /// </remarks>
        /// <example>
        /// For example, if the country is "United States", the Id might be 1, and if the country is "Canada", the Id might be 2. These IDs are used internally to manage relationships between countries and other entities in the database.
        /// </example>
        /// <seealso cref="CountryResponse.Id"/>
        public int Id { get; set; }
    }
}