namespace ASB.Services.v1.Dtos
{
    /// <summary>
    /// Data Transfer Object for User entity. This is used to transfer user data between layers of the application without exposing the internal structure of the User model.
    /// </summary>
    public class UserDto
    {
        /// <summary>
        /// Unique identifier for the user. This is typically generated by the database and is used to reference the user in other parts of the application.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// The username of the user. This is a unique identifier for the user that is used for authentication and display purposes. It should be unique across all users in the system.
        /// </summary>
        public required string Username { get; set; }
        /// <summary>
        /// The email address of the user. This is used for communication and may also be used for authentication purposes. It should be unique across all users in the system.
        /// </summary>
        public required string Email { get; set; }
        public int? UserGroupId { get; set; }
    }
}