namespace ASB.Admin.v1.Response
{

    using ASB.Services.v1.Dtos;
    using ASB.Admin.v1.Models;

    /// <summary>
    /// Response model for user-related API endpoints. This model is used to structure the data returned to clients when they request information about users. It typically contains a collection of UserDto objects, which represent individual users in the system.
    /// </summary>
    public class UserResponse
    {
        /// <summary>
        /// Unique identifier for the user. This is typically generated by the database and is used to
        /// reference the user in other parts of the application.
        /// </summary>
        /// <value>The unique identifier for the user.</value>
        public int Id { get; set; }

        /// <summary>
        /// The username of the user. This is a unique identifier for the user that is used for authentication and display purposes. It should be unique across all users in the system.
        /// </summary> <value>The username of the user.</value>
        public required string Username { get; set; }

        /// <summary> The email address of the user. This is used for communication and may also be used for authentication purposes. It should be unique across all users in the system. </summary>
        /// <value>The email address of the user.</value>
        public required string Email { get; set; }  
        public int? UserGroupId { get; set; }


        public static UserResponse DtoToUsers(UserDto userDto)
        {
            return new UserResponse
            {
                Id = userDto.Id,
                Username = userDto.Username,
                Email = userDto.Email,
                UserGroupId = userDto.UserGroupId
            };
        }

        /// <summary>
        /// A collection of UserDto objects representing the users in the system. Each UserDto contains basic information about a user, such as their ID, username, and email address.
        /// </summary>
        public static IEnumerable<UserModel> DtoListToUsersList(IEnumerable<UserDto> userDtos)
        {
            var userModels = userDtos.Select(dto => new UserModel
            {
                Id = dto.Id,
                Username = dto.Username,
                Email = dto.Email,
                UserGroupId = dto.UserGroupId
            }).ToList();

            return userModels;
        }
    }
}