// <auto-generated />
using System;
using ASB.Repositories.v1.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASB.Admin.Migrations
{
    [DbContext(typeof(AsbContext))]
    [Migration("20260503032132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Icon = "dashboard",
                            Name = "Dashboard",
                            Route = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Icon = "people",
                            Name = "User Management",
                            Route = "/users"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Icon = "bar_chart",
                            Name = "Reports",
                            Route = "/reports"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Icon = "settings",
                            Name = "Settings",
                            Route = "/settings"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Icon = "history",
                            Name = "Audit Logs",
                            Route = "/audit"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            Icon = "person",
                            Name = "Users",
                            ParentMenuId = 2,
                            Route = "/users/list"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 2,
                            Icon = "group",
                            Name = "Groups",
                            ParentMenuId = 2,
                            Route = "/users/groups"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            Icon = "admin_panel_settings",
                            Name = "Roles",
                            ParentMenuId = 2,
                            Route = "/users/roles"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            Icon = "assessment",
                            Name = "Activity Report",
                            ParentMenuId = 3,
                            Route = "/reports/activity"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 2,
                            Icon = "security",
                            Name = "Access Report",
                            ParentMenuId = 3,
                            Route = "/reports/access"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            Icon = "tune",
                            Name = "General",
                            ParentMenuId = 4,
                            Route = "/settings/general"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 2,
                            Icon = "lock",
                            Name = "Security",
                            ParentMenuId = 4,
                            Route = "/settings/security"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "*",
                            Description = "Grants full access to all resources.",
                            Name = "FullAccess",
                            Resource = "*"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Read",
                            Description = "Grants read-only access to resources.",
                            Name = "ReadOnly",
                            Resource = "*"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Write",
                            Description = "Allows managing users and groups.",
                            Name = "ManageUsers",
                            Resource = "User"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Read",
                            Description = "Allows viewing audit logs and reports.",
                            Name = "AuditAccess",
                            Resource = "AuditLog"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Viewer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.RoleMenuPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenuPermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            MenuId = 1,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 2,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 3,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 4,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 5,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 6,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 7,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 8,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 9,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 10,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 11,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 12,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 1,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 1,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 2,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 4,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 6,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 7,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 8,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 11,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 12,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 1,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 3,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 5,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 9,
                            PermissionLevel = "View"
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 10,
                            PermissionLevel = "View"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.RolePolicy", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("RolePolicies");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PolicyId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PolicyId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PolicyId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PolicyId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PolicyId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            PolicyId = 4
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@bank.com",
                            PasswordHash = "hashedpassword",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "Auditor"
                        },
                        new
                        {
                            Id = 4,
                            GroupName = "Viewer"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroupMapping", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "UserGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupMappings");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserGroupId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedBy = "system"
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroupRole", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserGroupRoles");

                    b.HasData(
                        new
                        {
                            UserGroupId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserGroupId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserGroupId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            UserGroupId = 4,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Menu", b =>
                {
                    b.HasOne("ASB.Repositories.v1.Entities.Menu", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.RoleMenuPermission", b =>
                {
                    b.HasOne("ASB.Repositories.v1.Entities.Menu", "Menu")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASB.Repositories.v1.Entities.Role", "Role")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.RolePolicy", b =>
                {
                    b.HasOne("ASB.Repositories.v1.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASB.Repositories.v1.Entities.Role", "Role")
                        .WithMany("RolePolicies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroupMapping", b =>
                {
                    b.HasOne("ASB.Repositories.v1.Entities.UserGroup", "UserGroup")
                        .WithMany("UserGroupMappings")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASB.Repositories.v1.Entities.User", "User")
                        .WithMany("UserGroupMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroupRole", b =>
                {
                    b.HasOne("ASB.Repositories.v1.Entities.Role", "Role")
                        .WithMany("UserGroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASB.Repositories.v1.Entities.UserGroup", "UserGroup")
                        .WithMany("UserGroupRoles")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenuPermissions");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.Role", b =>
                {
                    b.Navigation("RoleMenuPermissions");

                    b.Navigation("RolePolicies");

                    b.Navigation("UserGroupRoles");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.User", b =>
                {
                    b.Navigation("UserGroupMappings");
                });

            modelBuilder.Entity("ASB.Repositories.v1.Entities.UserGroup", b =>
                {
                    b.Navigation("UserGroupMappings");

                    b.Navigation("UserGroupRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
