server {
    listen 443 ssl;
    server_name magesh.com;

    ssl_certificate /etc/nginx/ssl/magesh.crt;
    ssl_certificate_key /etc/nginx/ssl/magesh.key;

    # UI app at /
    location / {
        proxy_pass http://asb-ui:80;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Swagger UI
    location /api/swagger/ {
        proxy_pass http://asb-api:8080/swagger/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Backend API
    location /api/ {
        proxy_pass http://asb-api:8080/api/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location = /api {
        return 301 /api/;
    }

    # Keycloak
    location /keycloak/ {
        proxy_pass http://keycloak:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port 443;

        proxy_redirect off;
    }

    location = /keycloak {
        return 301 /keycloak/;
    }
}

# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name magesh.com;

    return 301 https://$host$request_uri;
}